#!/usr/bin/env Rscript

# Load DESeq2 without printing package startup messages.
suppressPackageStartupMessages({
  library(DESeq2)
})

# Read command-line arguments passed from Snakemake.
args <- commandArgs(trailingOnly = TRUE)

# The script expects:
# 1) spike-in read-count table
# 2) output scale-factor table
# 3) comma-separated list of samples used for normalization
if (length(args) != 3) {
  stop(
    paste(
      "Usage: Rscript spikein_scale_factors.R",
      "<spike_reads_table.tsv>",
      "<scale_factors.tsv>",
      "<sample1,sample2,...>"
    )
  )
}

input_tsv <- args[1]
output_tsv <- args[2]
ip_samples_arg <- args[3]

# Convert the comma-separated sample argument into an R character vector.
ip_samples <- strsplit(
  ip_samples_arg,
  split = ",",
  fixed = TRUE
)[[1]]

ip_samples <- trimws(ip_samples)
ip_samples <- ip_samples[ip_samples != ""]

# Stop if no samples were provided for normalization.
if (length(ip_samples) == 0) {
  stop("No samples were provided for spike-in scale-factor calculation.")
}

# Read the spike-in read-count table generated by the pipeline.
df <- read.delim(
  input_tsv,
  header = TRUE,
  sep = "\t",
  stringsAsFactors = FALSE
)

# Check that the required columns are present.
required_cols <- c("sample", "spike_reads")
missing_cols <- setdiff(required_cols, colnames(df))

if (length(missing_cols) > 0) {
  stop(
    "Missing columns in input file: ",
    paste(missing_cols, collapse = ", ")
  )
}

# Check that every sample appears only once in the input table.
if (any(duplicated(df$sample))) {
  duplicated_samples <- unique(df$sample[duplicated(df$sample)])
  
  stop(
    "Duplicated samples found in input file: ",
    paste(duplicated_samples, collapse = ", ")
  )
}

# Check that all samples requested by Snakemake are present in the count table.
missing_ip_samples <- setdiff(ip_samples, df$sample)

if (length(missing_ip_samples) > 0) {
  stop(
    "The following samples are missing from the spike-in count table: ",
    paste(missing_ip_samples, collapse = ", ")
  )
}

# Keep only the samples selected for spike-in normalization.
# With peak calling enabled, these correspond to IP samples.
# With peak calling disabled, IP_SAMPLES is equal to SAMPLES.
df <- df[df$sample %in% ip_samples, , drop = FALSE]

# Preserve the sample order received from Snakemake.
df <- df[match(ip_samples, df$sample), , drop = FALSE]

# Convert spike-in read counts to numeric values.
spike_reads <- as.numeric(df$spike_reads)

# Stop if any spike-in count is missing or non-numeric.
if (any(is.na(spike_reads))) {
  stop("NA or non-numeric values found in spike_reads.")
}

# Scale factors cannot be calculated from zero or negative read counts.
if (any(spike_reads <= 0)) {
  bad <- df$sample[spike_reads <= 0]
  
  stop(
    "Samples with zero or negative spike-in reads found. ",
    "Scale factors cannot be calculated: ",
    paste(bad, collapse = ", ")
  )
}

# Assign sample names to the spike-in count vector.
names(spike_reads) <- df$sample

# Calculate scale factors relative to the median spike-in read count.
# Samples with fewer spike-in reads receive a larger scale factor.
median_count <- median(spike_reads)
scale_factor_median <- median_count / spike_reads

# Create a one-row count matrix for DESeq2 size-factor estimation.
count_mat <- matrix(
  as.integer(round(spike_reads)),
  nrow = 1
)

rownames(count_mat) <- "spike_in"
colnames(count_mat) <- names(spike_reads)

# Estimate DESeq2 size factors using only spike-in read counts.
deseq2_size_factor <- estimateSizeFactorsForMatrix(count_mat)

# bamCoverage multiplies the signal by --scaleFactor,
# so the inverse DESeq2 size factor is required.
scale_factor_deseq2 <- 1 / deseq2_size_factor

# Build the final output table.
out <- data.frame(
  sample = names(spike_reads),
  spike_reads = as.integer(round(spike_reads)),
  scale_factor_median = as.numeric(scale_factor_median),
  deseq2_size_factor = as.numeric(deseq2_size_factor),
  scale_factor_deseq2 = as.numeric(scale_factor_deseq2)
)

# Write the scale-factor table as a tab-separated file.
write.table(
  out,
  file = output_tsv,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)